version: '3.7'
services:
  flyway:
    image: boxfuse/flyway:5.2.4
    container_name: flyway_migration
    command: -url=jdbc:postgresql://db:5432/postgres -schemas=public -user=root -password=123456 -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db
    networks:
      - mall-backend

  db:
    image: daocloud.io/library/postgres:latest
    container_name: mall-database
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    networks:
      - mall-backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    container_name: mall-application
    volumes:
      - ./logs:/root/app/logs
    environment:
      - pg_user=root
      - pg_host=db
      - pg_pwd=123456
      - pg_db=postgres
      - pg_port=5432
    ports:
      - "7001:7000"
    networks:
      - mall-backend

networks:
  mall-backend: